export const TOGGLE_SIDEBAR = 'layout/Dashboard/TOGGLE_SIDEBAR';
export const FETCH_NOTIFICATIONS_NEW =
  'layout/Dashboard/FETCH_NOTIFICATIONS_NEW';
export const FETCH_NOTIFICATIONS_EARLIER =
  'layout/Dashboard/FETCH_NOTIFICATIONS_EARLIER';
export const FETCH_NOTIFICATIONS_SUCCESS_NEW =
  'layout/Dashboard/FETCH_NOTIFICATIONS_SUCCESS_NEW';
export const FETCH_NOTIFICATIONS_SUCCESS_EARLIER =
  'layout/Dashboard/FETCH_NOTIFICATIONS_SUCCESS_EARLIER';
export const FETCH_NOTIFICATIONS_FAILED =
  'layout/Dashboard/FETCH_NOTIFICATIONS_FAILED';
export const UPDATE_NOTIFICATION = 'layout/Dashboard/UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_COUNT =
  'layout/Dashboard/UPDATE_NOTIFICATION_COUNT';
export const FETCH_NEXT_NOTIFICATIONS =
  'layout/Dashboard/FETCH_NEXT_NOTIFICATIONS';
export const FETCH_NEXT_NOTIFICATIONS_SUCCESS =
  'layout/Dashboard/FETCH_NEXT_NOTIFICATIONS_SUCCESS';
export const MARK_NOTIFICATION_AS_READ =
  'layout/Dashboard/MARK_NOTIFICATION_AS_READ';
export const MARK_NOTIFICATION_AS_READ_FAILED =
  'layout/Dashboard/MARK_NOTIFICATION_AS_READ_FAILED';
export const MARK_NOTIFICATION_AS_READ_SUCCESS =
  'layout/Dashboard/MARK_NOTIFICATION_AS_READ_SUCCESS';
export const STOP_LAZY_LOAD = 'layout/Dashboard/STOP_LAZY_LOAD';
export const UPDATE_NOTIFICATION_MARK_AS_READ =
  'layout/Dashboard/UPDATE_NOTIFICATION_MARK_AS_READ';
export const FETCH_USER_SETTINGS = 'layout/Dashboard/FETCH_USER_SETTINGS';
export const FETCH_USER_SETTINGS_SUCCESS =
  'layout/Dashboard/FETCH_USER_SETTINGS_SUCCESS';
export const FETCH_USER_SETTINGS_FAILED =
  'layout/Dashboard/FETCH_USER_SETTINGS_FAILED';
export const UPDATE_USER_SETTINGS = 'layout/Dashboard/UPDATE_USER_SETTINGS';
export const UPDATE_USER_SETTINGS_SUCCESS =
  'layout/Dashboard/UPDATE_USER_SETTINGS_SUCCESS';
export const UPDATE_USER_SETTINGS_FAILED =
  'layout/Dashboard/UPDATE_USER_SETTINGS_FAILED';
export const TRIM_NOTIFICATIONS = 'layout/Dashboard/TRIM_NOTIFICATIONS';

export const REQUEST_SEND_FEEDBACK = 'layout/Dashboard/REQUEST_SEND_FEEDBACK';
export const REQUEST_SEND_FEEDBACK_SUCCESS =
  'layout/Dashboard/REQUEST_SEND_FEEDBACK_SUCCESS';
export const REQUEST_SEND_FEEDBACK_FAILED =
  'layout/Dashboard/REQUEST_SEND_FEEDBACK_FAILED';
export const SHOW_FEEDBACK_SUCCESS_MODAL =
  'layout/Dashboard/SHOW_FEEDBACK_SUCCESS_MODAL';
export const SHOW_FEEDBACK_FAILED_MODAL =
  'layout/Dashboard/SHOW_FEEDBACK_FAILED_MODAL';
export const REQUEST_ZOHO_USERS = 'layout/Dashboard/REQUEST_ZOHO_USERS';
export const SUCCESS_REQUEST_ZOHO_USERS = 'layout/Dashboard/SUCCESS_REQUEST_ZOHO_USERS';
export const FAILED_REQUEST_ZOHO_USERS = 'layout/Dashboard/FAILED_REQUEST_ZOHO_USERS';
export const SYNC_CRM_XERO = 'layout/Dashboard/SYNC_CRM_XERO';
export const SYNC_CRM_XERO_FAILED= 'layout/Dashboard/SYNC_CRM_XERO_FAILED';
export const SYNC_CRM_XERO_SUCCESS = 'layout/Dashboard/SYNC_CRM_XERO_SUCCESS';

